# Google Cloud Build configuration for Radiology RAG
steps:
  # Build Backend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/radiology-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/radiology-backend:latest'
      - '-f'
      - './backend/Dockerfile'
      - './backend'
    id: 'build-backend'

  # Build Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/radiology-frontend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/radiology-frontend:latest'
      - '-f'
      - './frontend/Dockerfile'
      - './frontend'
    id: 'build-frontend'

  # Push Backend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/radiology-backend:$COMMIT_SHA'
    id: 'push-backend'

  # Push Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/radiology-frontend:$COMMIT_SHA'
    id: 'push-frontend'

  # Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'radiology-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/radiology-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'ENVIRONMENT=production'
    id: 'deploy-backend'

  # Deploy Frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'radiology-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/radiology-frontend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '5'
    id: 'deploy-frontend'

images:
  - 'gcr.io/$PROJECT_ID/radiology-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/radiology-backend:latest'
  - 'gcr.io/$PROJECT_ID/radiology-frontend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/radiology-frontend:latest'

timeout: '1800s'
